stages:
  - docker-dev
  - deploy-dev
  - deploy-test
  - deploy-staging
  - docker-prd
  - deploy-prd

variables:
  IMAGE_TAG: alert.image.tag
  IMAGE_MC_SERVICE:  $CI_ALI_REGISTRY_DOMAIN/masastack/masa-mc-service:$CI_COMMIT_TAG
  IMAGE_MC_WEB_ADMIN_SERVER:  $CI_ALI_REGISTRY_DOMAIN/masastack/masa-mc-ui-admin:$CI_COMMIT_TAG

  IMAGE_MC_SERVICE_DEV:  $CI_ALI_REGISTRY_DOMAIN/masastack/masa-mc-service:dev-$CI_PIPELINE_ID
  IMAGE_MC_WEB_ADMIN_SERVER_DEV:  $CI_ALI_REGISTRY_DOMAIN/masastack/masa-mc-ui-admin:dev-$CI_PIPELINE_ID

  DOCKER_MC_SERVICE_PATH: ./src/Services/Masa.Mc.Service/Dockerfile
  DOCKER_MC_ADMIN_WEB_PATH: ./src/Web/Masa.Mc.Web.Admin.Server/Dockerfile

docker-dev:
  stage: docker-dev
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN 
  only:
    - main  
  script:
    - docker build -f $DOCKER_MC_SERVICE_PATH -t $IMAGE_MC_SERVICE_DEV .
    - docker push $IMAGE_MC_SERVICE_DEV 
    - docker build -f $DOCKER_MC_ADMIN_WEB_PATH -t $IMAGE_MC_WEB_ADMIN_SERVER_DEV .
    - docker push $IMAGE_MC_WEB_ADMIN_SERVER_DEV
  after_script:
    - docker rmi $IMAGE_MC_WEB_ADMIN_SERVER_DEV   
    - docker rmi $IMAGE_MC_SERVICE_DEV

deploy-dev:
  stage: deploy-dev
  image: registry.cn-hangzhou.aliyuncs.com/masa/library:helm3_latest
  only:
    - main
  before_script:
    - helm repo add masastack https://masastack.github.io/helm/
    - helm repo update
    - helm search repo masastack --devel --versions
  script:
    - echo $KUBE_CONFIG_MASA_YDY | base64 -d > ./config
    - echo $CI_PIPELINE_ID
    - helm --kubeconfig ./config upgrade --install masastack masastack/masastack --version 1.0.0-rc2 -n masastack-dev --set $IMAGE_TAG=dev-$CI_PIPELINE_ID -f ./values/values-dev.yaml
  retry: 2

deploy-test:
  stage: deploy-test
  image: registry.cn-hangzhou.aliyuncs.com/masa/library:helm3_latest
  only:
    - main
  before_script:
    - helm repo add masastack https://masastack.github.io/helm/
    - helm repo update
    - helm search repo masastack --devel --versions
  script:
    - echo $KUBE_CONFIG_MASA_YDY | base64 -d > ./config
    - echo $CI_PIPELINE_ID
    - helm --kubeconfig ./config upgrade --install masastack masastack/masastack --version 1.0.0-rc2 -n masastack-test --set $IMAGE_TAG=dev-$CI_PIPELINE_ID -f ./values/values-test.yaml
  retry: 2
  when: manual

deploy-staging:
  stage: deploy-staging
  image: registry.cn-hangzhou.aliyuncs.com/masa/library:helm3_latest
  only:
    - main
  before_script:
    - helm repo add masastack https://masastack.github.io/helm/
    - helm repo update
    - helm search repo masastack --devel --versions
  script:
    - echo $KUBE_CONFIG_MASA_YDY | base64 -d > ./config
    - echo $CI_PIPELINE_ID
    - helm --kubeconfig ./config upgrade --install masastack masastack/masastack --version 1.0.0-rc2 -n masastack-staging --set $IMAGE_TAG=dev-$CI_PIPELINE_ID -f ./values/values-staging.yaml
  retry: 2
  when: manual

docker-prd:
  stage: docker-prd
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN 
  only:
    - tags
  script:
    - docker build -f $AlertWebDockerFile -t $Alert_Web_Image .
    - docker push $Alert_Web_Image 
    - docker build -f $AlertServiceDockerFile -t $Alert_Service_Image .
    - docker push $Alert_Service_Image
  after_script:
    - docker rmi $Alert_Service_Image 
    - docker rmi $Alert_Web_Image

deploy-prd:
  stage: deploy-prd
  image: registry.cn-hangzhou.aliyuncs.com/masa/library:helm3_latest
  only:
    - tags
  before_script:
    - helm repo add masastack https://masastack.github.io/helm/
    - helm repo update
    - helm search repo masastack --devel --versions
  script:
    - echo $KUBE_CONFIG_MASA_PRD | base64 -d > ./config
    - echo $CI_COMMIT_TAG
    - helm --kubeconfig ./config upgrade --install masastack masastack/masastack --version 1.0.0-rc2 -n masastack --set $IMAGE_TAG=$CI_COMMIT_TAG -f ./values/values-prd.yaml
  retry: 2
  when: manual