stages:
  - docker-dev
  - deploy-dev
  - deploy-test
  - docker-prd
  - deploy-prd

variables:
  ALI_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_MC_SERVICE: $ALI_REGISTRY/masa/masa-mc-service:$CI_COMMIT_TAG
  IMAGE_MC_SERVICE_DEV: $ALI_REGISTRY/masa/masa-mc-service:dev-$CI_PIPELINE_ID
  IMAGE_MC_WEB_ADMIN_SERVER: $ALI_REGISTRY/masa/masa-mc-web-admin-server:$CI_COMMIT_TAG
  IMAGE_MC_WEB_ADMIN_SERVER_DEV: $ALI_REGISTRY/masa/masa-mc-web-admin-server:dev-$CI_PIPELINE_ID
  DOCKER_MC_SERVICE_PATH: ./src/Services/Masa.Mc.Service/Dockerfile
  DOCKER_MC_ADMIN_WEB_PATH: ./src/Web/Masa.Mc.Web.Admin.Server/Dockerfile
  NAMESPACE_DEV: masa-mc-dev
  NAMESPACE_TEST: masa-mc-test
  NAMESPACE_PRE: masa-mc-pre
  NAMESPACE_PRO: masa-mc

docker-build-dev:
  stage: docker-dev
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN 
  only:
    - main  
  script:
    - docker build -f $DOCKER_MC_SERVICE_PATH -t $IMAGE_MC_SERVICE_DEV .
    - docker push $IMAGE_MC_SERVICE_DEV 
    - docker build -f $DOCKER_MC_ADMIN_WEB_PATH -t $IMAGE_MC_WEB_ADMIN_SERVER_DEV .
    - docker push $IMAGE_MC_WEB_ADMIN_SERVER_DEV
  after_script:
    - docker rmi $IMAGE_MC_SERVICE_DEV   
    - docker rmi $IMAGE_MC_WEB_ADMIN_SERVER_DEV

deploy-dev:
  stage: deploy-dev
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN 
  only:
    - main  
  script:
    - echo $KUBE_CONFIG_DEV | base64 -d > ./config
    - kubectl --kubeconfig ./config set image deployment/masa-mc-service masa-mc-service=$IMAGE_MC_SERVICE_DEV -n $NAMESPACE_DEV
    - kubectl --kubeconfig ./config set image deployment/masa-mc-web-admin-server masa-mc-web-admin-server=$IMAGE_MC_WEB_ADMIN_SERVER_DEV -n $NAMESPACE_DEV
  retry: 2

deploy-test:
  stage: deploy-test
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN 
  only:
    - main  
  script:
    - echo $KUBE_CONFIG_DEV | base64 -d > ./config
    - kubectl --kubeconfig ./config set image deployment/masa-mc-service masa-mc-service=$IMAGE_MC_SERVICE_DEV -n $NAMESPACE_TEST
    - kubectl --kubeconfig ./config set image deployment/masa-mc-web-admin-server masa-mc-web-admin-server=$IMAGE_MC_WEB_ADMIN_SERVER_DEV -n $NAMESPACE_TEST
  retry: 2
  when: manual

docker-build-prd:
  stage: docker-prd
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN 
  only:
    - tags  
  script:
    - docker build -f $DOCKER_MC_SERVICE_PATH -t $IMAGE_MC_SERVICE .
    - docker push $IMAGE_MC_SERVICE 
    - docker build -f $DOCKER_MC_ADMIN_WEB_PATH -t $IMAGE_MC_WEB_ADMIN_SERVER .
    - docker push $IMAGE_MC_WEB_ADMIN_SERVER
  after_script:
    - docker rmi $IMAGE_MC_SERVICE 
    - docker rmi $IMAGE_MC_WEB_ADMIN_SERVER
  
deploy-prd:
  stage: deploy-prd
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN 
  only:
    - tags
  script:
    - echo $KUBE_CONFIG_BLAZOR_PRD | base64 -d > ./config
    - kubectl --kubeconfig ./config set image deployment/masa-mc-service masa-mc-service=$IMAGE_MC_SERVICE -n NAMESPACE_PRO
    - kubectl --kubeconfig ./config set image deployment/masa-mc-web-admin-server masa-mc-web-admin-server=$IMAGE_MC_WEB_ADMIN_SERVER -n NAMESPACE_PRO
  retry: 2
  when: manual