global using AliyunClient = AlibabaCloud.SDK.Dysmsapi20170525.Client;
global using AliyunConfig = AlibabaCloud.OpenApiClient.Models.Config;
global using AliyunSendSmsRequest = AlibabaCloud.SDK.Dysmsapi20170525.Models.SendSmsRequest;
global using System.Text.Json;
global using AlibabaCloud.SDK.Dysmsapi20170525.Models;
global using Microsoft.Extensions.Options;
global using Masa.Mc.Infrastructure.Sms.Response;
global using Masa.Mc.Infrastructure.Sms.Aliyun.Response.SmsTemplate;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;